### ISSUE TITLE
Ansible NOT Present

### ISSUE THREAD

**Issue by AmolMysql** [domflannery/mysql-sandbox#4]
Hi Dominique ,

Just finished Replication course
As per your MySQL Replication Tuts on Udemy, below does not reflect.  Kindly suggest ?

# Configuration 

Oracle VM VirtualBox :-
Version 5.2.6

Vagrant :- 
Installed Version: 2.0.2
Latest Version: 2.0.2

Windows 10 

# Issues 
 
1.)  As per tutorials did vagrant up, although the global-status is RUNNING  

D:\VM\mysql-sandbox-master\mysql-sandbox-master>D:\VM\Vagrant_setup\bin\vagrant global-status
id       name    provider   state   directory
------------------------------------------------------------------------------------
2708bc3  db1     virtualbox running D:/VM/mysql-sandbox-master/mysql-sandbox-master
c9027ca  db2     virtualbox running D:/VM/mysql-sandbox-master/mysql-sandbox-master
f9b7c32  ansible virtualbox running D:/VM/mysql-sandbox-master/mysql-sandbox-master

** Received below while starting all 3 VMs (db1,db2,ansible)

Bringing machine 'db1' up with 'virtualbox' provider...
Bringing machine 'db2' up with 'virtualbox' provider...
Bringing machine 'ansible' up with 'virtualbox' provider...
==> db1: Importing base box 'domflannery/centos7'...
==> db1: Matching MAC address for NAT networking...
==> db1: Checking if box 'domflannery/centos7' is up to date...
==> db1: Setting the name of the VM: mysql-sandbox-master_db1_1519028509178_62282
==> db1: Clearing any previously set network interfaces...
==> db1: Preparing network interfaces based on configuration...
    db1: Adapter 1: nat
    db1: Adapter 2: hostonly
==> db1: Forwarding ports...
    db1: 22 (guest) => 2203 (host) (adapter 1)
==> db1: Booting VM...
==> db1: Waiting for machine to boot. This may take a few minutes...
    db1: SSH address: 127.0.0.1:2203
    db1: SSH username: vagrant
    db1: SSH auth method: private key
    db1: Warning: Connection reset. Retrying...
    db1: Warning: Remote connection disconnect. Retrying...
    db1: Warning: Connection aborted. Retrying...
    db1: Warning: Connection reset. Retrying...
    db1: Warning: Remote connection disconnect. Retrying.
	
2.) Logged in to Putty on Ansible VM i.e (127.0.0.1 port : 2205) as per Vagrant File 

But NO shared ansible directory present, PFB :-

login as: vagrant
vagrant@127.0.0.1's password:
Last login: Sun Nov 26 13:44:52 2017 from gateway
MySQL sandbox https://github.com/domflannery/mysql-sandbox

[vagrant@centos ~]$ cd ansible
-bash: cd: ansible: No such file or directory
[vagrant@centos ~]$

**Comment by domflannery** [comment]
It looks like the vm didn't start. Were you able to retry starting the vms by doing a vagrant destroy and vagrant up? I can tell that they didn't fully start because when you logged in, it says vagrant@centos instead of vagrant@db1 or similar. Changing the hostname is part of the start up process.
