### ISSUE TITLE
ansible-playbook: command not found

### ISSUE THREAD

**Issue by nmadurawela** [domflannery/mysql-sandbox#6]
Help me on the following issue which was prompted while I was installing MySQL on two db nodes.

[vagrant@ansible ansible]$ ansible-playbook database.yml -i inventory --extra-vars "mysql_variant=mysql mysql_version=56 hosts=db1,db2"
**-bash: ansible-playbook: command not found**

**Comment by domflannery** [comment]
​When you did the vagrant up, did you see any errors towards the end of the ansible vm starting up? Ansible gets installed during the vagrant up process. If you're not sure, I'd run vagrant destroy ansible, then vagrant up ansible and pay close attention to the output. It's possible that there was a temporary error that may no longer be an issue. Also, you'll need to make sure you're connected to the internet.
