### ISSUE TITLE
Any plans to update course, and/or use docker? 

### ISSUE THREAD

**Issue by carehart** [domflannery/mysql-sandbox#7]
Thanks for all your efforts in the course and here. Just curious if you may be considering updating things since 2017, and/or switching to or at least showing also use of Docker.

If you've switched priorities or work on this is no longer interesting, perhaps others could take up the effort. Just curious to hear your thoughts first. Maybe you've even learned something that we'd benefit knowing before taking that on. :)

**Comment by domflannery** [comment]
Hello @carehart my priorities over the past few years have in fact changed. I created this sandbox for a course I created on Udemy called [MySQL Replication (Beginner)](https://www.udemy.com/course/mysql-replication-beginner/?referralCode=45EA51C0EDDA6556ECAF). Shortly after I created the course, the company I was working for at the time was planning on migrating to AWS. Therefore I focused my free time on learning everything I could about AWS so we could be successful in our migration. Last October, I started a new job and have been focused on making sure I'm successful in my new position.

I do plan within the next few years to consider creating more courses for MySQL and possibly AWS as well. As for the current replication course, my intent for it was to merely teach the basics of MySQL replication that I struggled to find when I was first learning it. As for what those courses will look like, that will depend on the trends of the time. 

As for this sandbox, I still use it as is to quickly spin up vm's to test different replication topologies and it's free for others to fork if they'd like to take it a different direction. For me, I need to be careful of changes I make to ensure it works for the students of my course. The one update I'll likely make soon is to add the ability to select MySQL 8.0.

**Comment by carehart** [comment]
Thanks. I wondered if it may have involved a move by you to aws rds as well, so perhaps changing more to configuration-as-code rather than vm's or even containers.  But I didn't want to make the note too long with speculatons. :) 

BTW, I had acknowledged awareness of the course in my first sentence. Indeed I had seen the course first, which led me here. And to be clear, I was in fact asking about modifying them both. And I was even asking about your openness to others helping with both, if they were able. 

I'll assume you saw that, and are still inclined to leave it as-is for the foreseeable future, until you may get to updating things.

FWIW, this is still among only a couple of Udemy courses on mysql replication in any form. I thought that might motivate evolving it in a couple of directions. But besides your being otherwise occupied, I wonder if perhaps a low sign-up rate might be reducing motivation. This is what I was alluding to as a possiblity in my last sentence. :)

**Comment by domflannery** [comment]
I did notice your acknowledgement of my course, but thought I'd mention it my response for those that might come across this without knowledge of my course. 

As for your assumption of low enrollments being a factor, you're also correct. I can only speculate that students want longer more broadly focused courses. My preference as an instructor is to have smaller focused courses without a lot of unnecessary commentary that doesn't add to the learning experience.
